name: study_deadline_exam_planner
description: A Study Deadline & Exam Planner (offline-first, SQLite, notifications).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # Local database
  sqflite: ^2.3.0
  path_provider: ^2.1.2

  # Notifications
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.3

  # Charts & calendar
  fl_chart: ^0.69.0
  table_calendar: ^3.1.2

  # Utils
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  file_picker: ^8.0.0+1

  # Material design localizations
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

